site_name: Azimuth Deployment Documentation
repo_url: https://github.com/stackhpc/azimuth-config
copyright: Copyright &copy; StackHPC
edit_uri: ''

nav:
  - Home: index.md
  - environments.md
  - setup.md
  - Azimuth Configuration:
      - Introduction: configuration/index.md
      - configuration/prerequisites.md
      - configuration/deployment-method.md
      - configuration/target-cloud.md
      - configuration/secret-key.md
      - configuration/ingress.md
      - configuration/zenith.md
      - configuration/community-images.md
      - configuration/kubernetes.md
      - configuration/caas.md
  - secrets.md
  - terraform.md
  - deployment.md
  - debugging.md

theme:
  features:
    - navigation.tracking
  name: material

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
