site_name: Azimuth Deployment Documentation
repo_url: https://github.com/stackhpc/azimuth-config
copyright: Copyright &copy; StackHPC 2022
edit_uri: ''

nav:
  - Home: index.md
  - try.md
  - environments.md
  - Repository:
      - repository/index.md
      - repository/secrets.md
      - repository/terraform.md
  - Configuration:
      - configuration/index.md
      - configuration/prerequisites.md
      - configuration/deployment-method.md
      - configuration/target-cloud.md
      - configuration/secret-key.md
      - configuration/ingress.md
      - configuration/zenith.md
      - configuration/community-images.md
      - configuration/kubernetes.md
      - configuration/caas.md
  - Deployment:
      - deployment/index.md
      - deployment/automation.md
  - Debugging:
      - debugging/index.md
      - debugging/access-k3s.md
      - debugging/access-ha.md
      - debugging/access-monitoring.md
      - debugging/zenith-services.md
      - debugging/kubernetes.md
      - debugging/caas.md

theme:
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
  name: material

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
