---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: dcb3b6a97bfc67e41d5baf56e529c8ec8e997511
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
