---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 7389b226059e350dde43dfe3c27a1ea84ccb8cdd
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
