---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 0c3eb63 # Bump slurm image for slurm app v1.126 to support containerised workloads
