---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: d78d51c5cb1a200b8bdd66b153c5ed9ba76632b3
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
