---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 8cfc9eee5717cfc80321be398805f860d92a2a44
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
