#####
# This file contains variables related to the images managed by Azimuth
#####

# Sets the target disk format for community images when uploaded to the cloud
# azimuth-ops will convert images where this differs from the source format
infra_community_images_target_disk_format: qcow2

# Defines the images that will uploaded to the target cloud as community images
infra_community_images:
  # Ubuntu 20.04 image, primarily for the K3S seed
  ubuntu_2004_20220712:
    name: Ubuntu-Focal-20.04-20220712
    source_url: https://cloud-images.ubuntu.com/focal/20220712/focal-server-cloudimg-amd64.img
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"

  # Cluster API images supporting different Kubernetes versions
  # See https://github.com/osism/k8s-capi-images
  kube_1_22_11:
    name: ubuntu-2004-kube-v1.22.11
    source_url: https://minio.services.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-v1.22/ubuntu-2004-kube-v1.22.11.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"
  kube_1_23_8:
    name: ubuntu-2004-kube-v1.23.8
    source_url: https://minio.services.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-v1.23/ubuntu-2004-kube-v1.23.8.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"
  kube_1_24_2:
    name: ubuntu-2004-kube-v1.24.2
    source_url: https://minio.services.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-v1.24/ubuntu-2004-kube-v1.24.2.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"

  # Images for CaaS appliances
  # See https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_f0dc9cb312144d0aa44037c9149d2513/azimuth-images-prerelease/ for builds
  repo2docker_20220712_0914:
    name: ubuntu-focal-jupyter-repo2docker-220712-0914
    source_url: https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_f0dc9cb312144d0aa44037c9149d2513/azimuth-images-prerelease/ubuntu-focal-jupyter-repo2docker-220712-0914.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"

  workstation_20220711_2135:
    name: ubuntu-focal-desktop-220711-2135
    source_url: https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_f0dc9cb312144d0aa44037c9149d2513/azimuth-images-prerelease/ubuntu-focal-desktop-220711-2135.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"

  rocky_8_20220702:
    name: Rocky8-20220702
    source_url: http://download.rockylinux.org/pub/rocky/8.6/images/Rocky-8-GenericCloud-8.6.20220702.0.x86_64.qcow2
    source_disk_format: qcow2
    container_format: bare
    disk_format: "{{ infra_community_images_target_disk_format }}"

# The key of the image in infra_community_images to use for the seed/single node
infra_image_key: ubuntu_2004_20220712

# The Kubernetes version that will be used for the HA cluster
capi_cluster_kubernetes_version: 1.23.8
# The ID of the image to use for the HA Azimuth cluster
capi_cluster_machine_image_id: "{{ infra_community_image_info.kube_1_23_8 }}"

# The ID of a Rocky 8 image that will be used for Slurm clusters
azimuth_caas_stackhpc_slurm_appliance_image: "{{ infra_community_image_info.rocky_8_20220702 }}"
# The ID of the desktop or webconsole image to use for the workstation appliance
azimuth_caas_stackhpc_workstation_image: "{{ infra_community_image_info.workstation_20220711_2135 }}"
# The ID of the repo2docker image to use for the repo2docker appliance
azimuth_caas_stackhpc_repo2docker_image: "{{ infra_community_image_info.repo2docker_20220712_0914 }}"

# The IDs of the Kubernetes images for each supported version
azimuth_capi_operator_kube_1_22_11_image: "{{ infra_community_image_info.kube_1_22_11 }}"
azimuth_capi_operator_kube_1_23_8_image: "{{ infra_community_image_info.kube_1_23_8 }}"
azimuth_capi_operator_kube_1_24_2_image: "{{ infra_community_image_info.kube_1_24_2 }}"
