#####
# This file defines the available Kubernetes cluster templates
#
# Templates can be defined in any way that the operator desires
# Here, a mixin approach is demonstrated to avoid duplication between templates
#####

azimuth_capi_operator_mixin_kube_1_21_11:
  global:
    kubernetesVersion: 1.21.11
  machineImageId: "{{ infra_community_image_info.kube_1_21_11 }}"

azimuth_capi_operator_mixin_kube_1_22_8:
  global:
    kubernetesVersion: 1.22.8
  machineImageId: "{{ infra_community_image_info.kube_1_22_8 }}"

azimuth_capi_operator_mixin_kube_1_23_5:
  global:
    kubernetesVersion: 1.23.5
  machineImageId: "{{ infra_community_image_info.kube_1_23_5 }}"

# This mixin provisions Kubernetes nodes on the same network that Azimuth creates for
# regular VMs, rather than each cluster having its own network
azimuth_capi_operator_mixin_portal_net:
  clusterNetworking:
    internalNetwork:
      networkFilter:
        tags: portal-internal

# This mixin provisions Kubernetes nodes on an SR-IOV enabled VLAN, with SR-IOV enabled ports
# This requires that a VLAN with the given tag is made available to each project (it doesn't
# have to be the same VLAN, but the tag must be present)
azimuth_capi_operator_mixin_sriov:
  clusterNetworking:
    internalNetwork:
      networkFilter:
        tags: sriov-vlan
  controlPlane:
    machineNetworking:
      ports:
        - vnicType: direct
  nodeGroupDefaults:
    machineNetworking:
      ports:
        - vnicType: direct
  # Because SR-IOV ports don't have any port security, we can tell
  # Calico that it only needs to apply the VXLAN at the cluster boundary
  addons:
    cni:
      calico:
        installation:
          calicoNetwork:
            ipPools:
              - cidr: __KUBEADM_POD_CIDR__
                encapsulation: VXLANCrossSubnet

# Build the templates by composing the mixins together
azimuth_capi_operator_cluster_templates:
  - name: kube-1-21-11
    label: v1.21.11
    description: Kubernetes 1.21.11 with HA control plane.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_21_11 |
          combine(azimuth_capi_operator_mixin_portal_net)
      }}
  - name: kube-1-22-8
    label: v1.22.8
    description: Kubernetes 1.22.8 with HA control plane.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_22_8 |
          combine(azimuth_capi_operator_mixin_portal_net)
      }}
  - name: kube-1-23-5
    label: v1.23.5
    description: Kubernetes 1.23.5 with HA control plane.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_23_5 |
          combine(azimuth_capi_operator_mixin_portal_net)
      }}
  - name: kube-1-21-11-sriov
    label: v1.21.11 / SR-IOV
    description: Kubernetes 1.21.11 with HA control plane and SR-IOV enabled networking.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_21_11 |
          combine(azimuth_capi_operator_mixin_sriov)
      }}
  - name: kube-1-22-8-sriov
    label: v1.22.8 / SR-IOV
    description: Kubernetes 1.22.8 with HA control plane and SR-IOV enabled networking.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_22_8 |
          combine(azimuth_capi_operator_mixin_sriov)
      }}
  - name: kube-1-23-5-sriov
    label: v1.23.5 / SR-IOV
    description: Kubernetes 1.23.5 with HA control plane and SR-IOV enabled networking.
    values: >-
      {{
        azimuth_capi_operator_mixin_kube_1_23_5 |
          combine(azimuth_capi_operator_mixin_sriov)
      }}
