name: Demo env deployment test
on:
  pull_request:
    # NOTE: Avoid running on draft PRs to save on resources
    types: ready_for_review
    branches:
      - main
jobs:
  deploy_demo_env:
    uses: ./.github/workflows/demo-deploy.yml
    secrets: inherit
    # NOTE: Github docs claim that workflows should automatically await approval on PRs from external
    # forks but haven't tested this explicitly so keep this conditional just in case
    # (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
    if: github.repository == 'stackhpc/azimuth-config'